name: Question
description: 'Want to learn more about the launcher?'
title: "[Question] <Short description>"
labels: [question]
body:
- type: textarea
  id: version
  attributes:
    label: Ask the question here.
    description: |
      Be descriptive in your question so that we can provide an equally descriptive answer. Make sure you've checked out the subreddit or the README before asking, as your question might already have an answer.
    placeholder: 'Example: Login results in a crash'
  validations:
    required: true